function(print_system_dependencies_info)
    if (OpenGL_FOUND)
        message("${Blue}OpenGL Found${ColorReset}")
    else ()
        message(FATAL_ERROR "OpenGL Not Found")
    endif ()

    if (CURL_FOUND)
        message("${Blue}Curl Version: ${Green}${CURL_VERSION_STRING}${ColorReset}")
    else ()
        message(FATAL_ERROR "CURL Not Found")
    endif ()

    if (OPENSSL_FOUND)
        message("${Blue}Open SSL Version: ${Green}${OPENSSL_VERSION}${ColorReset}")
    else ()
        message(FATAL_ERROR "Open SSL Not Found")
    endif ()

    if (unofficial-minizip_VERSION)
        get_target_property(MINIZIP_INCLUDE_DIR unofficial::minizip::minizip INTERFACE_INCLUDE_DIRECTORIES)

        message("${Blue}MiniZip Version: ${Green}${unofficial-minizip_VERSION}")
    else ()
        message(FATAL_ERROR "MiniZip Not Found")
    endif ()

    if (WIN32)
        if (WinToast_LIBRARY_DEBUG)
            message("${Blue}WinToast Found: ${Green}${WinToast_LIBRARY_DEBUG} ${ColorReset}")
        elseif (WinToast_LIBRARY_RELEASE)
            message("${Blue}WinToast Found: ${Green}${WinToast_LIBRARY_RELEASE} ${ColorReset}")
        else ()
            message(FATAL_ERROR "WinToast Not Found")
        endif ()
    endif ()
endfunction()